[options]
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    enable_guicolors = true

    statusline_separator = "arrow"
    statusline_iseparator = "arrow"

    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    default_indent = 4

    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

    windows_smartclose = "Q"
    escape_key_binding = ""

    autocomplete_method = "coc"

[[layers]]
    name = "ui"
    enable_indentline = true
[[layers]]
    name = "autocomplete"
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"
[[layers]]
    name = "shell"
    default_position = "bottom"
    default_height = 30
[[layers]]
    name = "tools"
[[layers]]
    name = "sudo"
[[layers]]
    name = "fzf"
[[layers]]
    name = "VersionControl"

[[layers]]
    name = "lsp"
    filetypes = [
        "c",
        "cpp",
        "go",
        "python",
        "rust"
    ]
    [layers.override_cmd]
        go = ["gopls"]
[[layers]]
    name = "lang#c"
[[layers]]
    name = "lang#go"
[[layers]]
    name = "lang#rust"
[[layers]]
    name = "lang#python"
[[layers]]
    name = "lang#markdown"
[[layers]]
    name = "lang#sh"

[[custom_plugins]]
    repo = "tpope/vim-sleuth"

