# set keymap for X
setxkbmap gb

# autolock
xss-lock i3lock -i ~/.wallpaper.png

# disk mounting
udiskie &

# GTK/QT theming
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0

# run ssh-agent
eval $(ssh-agent)

# wallpaper
~/.fehbg &

# launch desktop
compton -b
exec i3
