" evim will already have done these settings
if v:progname =~? 'evim'
  finish
endif

" get defaults
source $VIMRUNTIME/defaults.vim

" plugins
call plug#begin('~/.vim/plugged')

  " editing
  Plug 'tpope/vim-sleuth'
  Plug 'jiangmiao/auto-pairs'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-repeat'

  " GUI stuff
  Plug 'scrooloose/nerdtree'
  Plug 'airblade/vim-gitgutter'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'

  " Misc
  Plug 'jpalardy/vim-slime'

call plug#end()

" backups
if has('vms')
  set nobackup
else
  set nobackup
  set writebackup
  if has('persistent_undo')
    set undofile
    set undodir=$HOME/.vim/undo//
  endif
endif

" swap
set directory=$HOME/.vim/swap//
set updatetime=100

if &t_Co > 2 || has('gui_running')
  " switch on highlighting the last used search pattern.
  set hlsearch
endif

if has('autocmd')
  augroup vimrcEx
  au!

  autocmd FileType text setlocal textwidth=78

  augroup END
else
  set autoindent
endif

" matchit
if has('syntax') && has('eval')
  packadd! matchit
endif

" clipboard
set clipboard=unnamedplus

" gutter
set number
map <C-n> :NERDTreeToggle<CR>

" theming
colorscheme custom
let g:airline_theme='term'
if !has('gui_running')
  let g:airline_powerline_fonts = 1
endif

" slime
let g:slime_target = 'vimterminal'

" folding
set foldmethod=syntax
autocmd BufRead * normal zR

" default indentation settings
set shiftwidth=4
set tabstop=4

" assorted keybindings
noremap Y y$
nmap <silent> ss :wincmd w<CR>
nmap <silent> sj :wincmd j<CR>
nmap <silent> sk :wincmd k<CR>
nmap <silent> sh :wincmd h<CR>
nmap <silent> sl :wincmd l<CR>
nmap <silent> sJ :wincmd J<CR>
nmap <silent> sK :wincmd K<CR>
nmap <silent> sH :wincmd H<CR>
nmap <silent> sL :wincmd L<CR>
