" evim will already have done these settings
if v:progname =~? "evim"
  finish
endif

" get defaults
source $VIMRUNTIME/defaults.vim

" plugins
call plug#begin('~/.vim/plugged')

  Plug 'scrooloose/nerdtree'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'airblade/vim-gitgutter'

  Plug 'Valloric/YouCompleteMe'

call plug#end()

" backups
if has("vms")
  set nobackup
else
  set nobackup
  set writebackup
  if has('persistent_undo')
    set undofile
    set undodir=$HOME/.vim/undo//
  endif
endif

" swap
set directory=$HOME/.vim/swap//
set updatetime=500

if &t_Co > 2 || has("gui_running")
  " switch on highlighting the last used search pattern.
  set hlsearch
endif

if has("autocmd")
  augroup vimrcEx
  au!

  autocmd FileType text setlocal textwidth=78

  augroup END
else
  set autoindent
endif

" matchit
if has('syntax') && has('eval')
  packadd! matchit
endif

" gutter
set number
highlight LineNr ctermfg=darkgrey

map <C-n> :NERDTreeToggle<CR>

" theming
let g:airline_theme='term'

if !has("gui_running")
  let g:airline_powerline_fonts = 1
endif

" autocompletion
set completeopt=menu,longest,preview
