# set PATH
## generic
PATH=$PATH:~/bin:~/.local/bin
## ruby gems
if [[ -d ~/.gem/ruby/ ]]; then
	for f in ~/.gem/ruby/*; do
		PATH=$PATH:$f/bin
	done
fi
## go
PATH=$PATH:~/go/bin
## rust
PATH=$PATH:~/.cargo/bin

export PATH

# startx
if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
	exec startx
fi
