export VISUAL=vim
export EDITOR=vim

# generic
PATH=$PATH:~/bin:~/.local/bin
# ruby gems
if [[ -d ~/.gem/ruby/ ]]; then
	for f in ~/.gem/ruby/*; do
		PATH=$PATH:$f/bin
	done
fi
# go
if [[ -d ~/go/bin/ ]]; then
	PATH=$PATH:~/go/bin
fi
# rust
if [[ -d ~/.cargo/bin/ ]]; then
	PATH=$PATH:~/.cargo/bin
fi
# dotnet
if [[ -d ~/.dotnet/tools/ ]]; then
	PATH=$PATH:~/.dotnet/tools
fi
export PATH

